  	 								      					 void main(){
	pushi(0);
	pushi(ebp);
	move(esp, ebp);
	addi(-28, esp);
	move(5, edx);
	move(0, ecx);
	muli(4, ecx);
	move(-20, ebx);
	addi(ebx, ecx);
	addi(ebp, ecx);
	storei(edx, ind(ecx));
	move(0, edx);
	muli(4, edx);
	move(-20, ecx);
	addi(ecx, edx);
	addi(ebp, edx);
	loadi(ind(edx),  edx);
	move(1, ecx);
	muli(4, ecx);
	move(-20, ebx);
	addi(ebx, ecx);
	addi(ebp, ecx);
	storei(edx, ind(ecx));
	move(2, ecx);
	muli(4, ecx);
	move(-20, ebx);
	addi(ebx, ecx);
	addi(ebp, ecx);
	storei(edx, ind(ecx));
	move(3, ecx);
	muli(4, ecx);
	move(-20, ebx);
	addi(ebx, ecx);
	addi(ebp, ecx);
	storei(edx, ind(ecx));
	move(0, edx);
	move(-28, ecx);
	addi(ebp, ecx);
	storei(edx, ind(ecx));
	l2: ;
	move(5, edx);
	loadi(ind(ebp, -28),  ecx);
	cmpi(ecx, edx);
	jl(l0);
	move(0, edx);
	j(l1);
	l0: ;
	move(1, edx);
	l1: ;
	cmpi(0, edx);
	je(l3);
	move(-28, edx);
	addi(ebp, edx);
	loadi(ind(edx), ecx);
	addi(1, ecx);
	storei(ecx, ind(edx));
	move(ecx, edx);
	addi(-1, edx);
	muli(4, edx);
	move(-20, ecx);
	addi(ecx, edx);
	addi(ebp, edx);
	loadi(ind(edx), ecx);
	addi(1, ecx);
	storei(ecx, ind(edx));
	move(ecx, edx);
	addi(-1, edx);
	loadi(ind(ebp, -28),  ecx);
	muli(4, ecx);
	move(-20, ebx);
	addi(ebx, ecx);
	addi(ebp, ecx);
	storei(edx, ind(ecx));
	move(-28, edx);
	addi(ebp, edx);
	loadi(ind(edx), ecx);
	addi(1, ecx);
	storei(ecx, ind(edx));
	move(ecx, edx);
	addi(-1, edx);
	j(l2);
	l3: ;
	move(0, edx);
	move(-24, ecx);
	addi(ebp, ecx);
	storei(edx, ind(ecx));
	l6: ;
	move(5, edx);
	loadi(ind(ebp, -24),  ecx);
	cmpi(ecx, edx);
	jl(l4);
	move(0, edx);
	j(l5);
	l4: ;
	move(1, edx);
	l5: ;
	cmpi(0, edx);
	je(l7);
	loadi(ind(ebp, -24),  edx);
	muli(4, edx);
	move(-20, ecx);
	addi(ecx, edx);
	addi(ebp, edx);
	loadi(ind(edx),  edx);
	print_int(edx);
	print_string("\n");
	move(-24, edx);
	addi(ebp, edx);
	loadi(ind(edx), ecx);
	addi(1, ecx);
	storei(ecx, ind(edx));
	move(ecx, edx);
	addi(-1, edx);
	j(l6);
	l7: ;
	move(0, edx);
	storei(edx, ind(ebp, 4));
	j(e);
	e: ;
	move(ebp, esp);
	loadi(ind(ebp), ebp);
	popi(1);
	return;
	popi(0);
}

