// Generated by Bisonc++ V4.05.00 on Fri, 17 Apr 2015 19:57:19 +0530

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {300, 1}, // 1: translation_unit ->  function_definition
     {300, 2}, // 2: translation_unit ->  translation_unit function_definition
     {301, 5}, // 3: function_definition ->  type_specifier #0001 fun_declarator #0002 compound_statement
     {302, 0}, // 4: #0001 ->  <empty>
     {303, 0}, // 5: #0002 ->  <empty>
     {304, 1}, // 6: type_specifier (VOID) ->  VOID
     {304, 1}, // 7: type_specifier (INT) ->  INT
     {304, 1}, // 8: type_specifier (FLOAT) ->  FLOAT
     {305, 4}, // 9: fun_declarator (IDENTIFIER) ->  IDENTIFIER '(' parameter_list ')'
     {305, 3}, // 10: fun_declarator (IDENTIFIER) ->  IDENTIFIER '(' ')'
     {306, 1}, // 11: parameter_list ->  parameter_declaration
     {306, 3}, // 12: parameter_list (',') ->  parameter_list ',' parameter_declaration
     {307, 2}, // 13: parameter_declaration ->  type_specifier declarator
     {308, 1}, // 14: declarator (IDENTIFIER) ->  IDENTIFIER
     {308, 4}, // 15: declarator ('[') ->  declarator '[' constant_expression ']'
     {309, 1}, // 16: constant_expression (INT_CONSTANT) ->  INT_CONSTANT
     {309, 1}, // 17: constant_expression (FLOAT_CONSTANT) ->  FLOAT_CONSTANT
     {310, 2}, // 18: compound_statement ('{') ->  '{' '}'
     {310, 3}, // 19: compound_statement ('{') ->  '{' statement_list '}'
     {310, 4}, // 20: compound_statement ('{') ->  '{' declaration_list statement_list '}'
     {312, 1}, // 21: statement_list ->  statement
     {312, 2}, // 22: statement_list ->  statement_list statement
     {313, 3}, // 23: statement ('{') ->  '{' statement_list '}'
     {313, 1}, // 24: statement ->  selection_statement
     {313, 1}, // 25: statement ->  iteration_statement
     {313, 1}, // 26: statement ->  assignment_statement
     {313, 3}, // 27: statement (RETURN) ->  RETURN expression ';'
     {313, 4}, // 28: statement (IDENTIFIER) ->  IDENTIFIER '(' ')' ';'
     {313, 5}, // 29: statement (IDENTIFIER) ->  IDENTIFIER '(' expression_list ')' ';'
     {314, 1}, // 30: assignment_statement (';') ->  ';'
     {314, 4}, // 31: assignment_statement ('=') ->  l_expression '=' expression ';'
     {315, 1}, // 32: expression ->  logical_and_expression
     {315, 3}, // 33: expression (OR_OP) ->  expression OR_OP logical_and_expression
     {316, 1}, // 34: logical_and_expression ->  equality_expression
     {316, 3}, // 35: logical_and_expression (AND_OP) ->  logical_and_expression AND_OP equality_expression
     {317, 1}, // 36: equality_expression ->  relational_expression
     {317, 3}, // 37: equality_expression (EQ_OP) ->  equality_expression EQ_OP relational_expression
     {317, 3}, // 38: equality_expression (NE_OP) ->  equality_expression NE_OP relational_expression
     {318, 1}, // 39: relational_expression ->  additive_expression
     {318, 3}, // 40: relational_expression ('<') ->  relational_expression '<' additive_expression
     {318, 3}, // 41: relational_expression ('>') ->  relational_expression '>' additive_expression
     {318, 3}, // 42: relational_expression (LE_OP) ->  relational_expression LE_OP additive_expression
     {318, 3}, // 43: relational_expression (GE_OP) ->  relational_expression GE_OP additive_expression
     {319, 1}, // 44: additive_expression ->  multiplicative_expression
     {319, 3}, // 45: additive_expression ('+') ->  additive_expression '+' multiplicative_expression
     {319, 3}, // 46: additive_expression ('-') ->  additive_expression '-' multiplicative_expression
     {320, 1}, // 47: multiplicative_expression ->  unary_expression
     {320, 3}, // 48: multiplicative_expression ('*') ->  multiplicative_expression '*' unary_expression
     {320, 3}, // 49: multiplicative_expression ('/') ->  multiplicative_expression '/' unary_expression
     {321, 1}, // 50: unary_expression ->  postfix_expression
     {321, 2}, // 51: unary_expression ->  unary_operator postfix_expression
     {322, 1}, // 52: postfix_expression ->  primary_expression
     {322, 3}, // 53: postfix_expression (IDENTIFIER) ->  IDENTIFIER '(' ')'
     {322, 4}, // 54: postfix_expression (IDENTIFIER) ->  IDENTIFIER '(' expression_list ')'
     {322, 2}, // 55: postfix_expression (INC_OP) ->  l_expression INC_OP
     {323, 1}, // 56: primary_expression ->  l_expression
     {323, 3}, // 57: primary_expression ('=') ->  l_expression '=' expression
     {323, 1}, // 58: primary_expression (INT_CONSTANT) ->  INT_CONSTANT
     {323, 1}, // 59: primary_expression (FLOAT_CONSTANT) ->  FLOAT_CONSTANT
     {323, 1}, // 60: primary_expression (STRING_LITERAL) ->  STRING_LITERAL
     {323, 3}, // 61: primary_expression ('(') ->  '(' expression ')'
     {324, 1}, // 62: l_expression (IDENTIFIER) ->  IDENTIFIER
     {324, 4}, // 63: l_expression ('[') ->  l_expression '[' expression ']'
     {325, 1}, // 64: expression_list ->  expression
     {325, 3}, // 65: expression_list (',') ->  expression_list ',' expression
     {326, 1}, // 66: unary_operator ('-') ->  '-'
     {326, 1}, // 67: unary_operator ('!') ->  '!'
     {327, 7}, // 68: selection_statement (IF) ->  IF '(' expression ')' statement ELSE statement
     {328, 5}, // 69: iteration_statement (WHILE) ->  WHILE '(' expression ')' statement
     {328, 9}, // 70: iteration_statement (FOR) ->  FOR '(' expression ';' expression ';' expression ')' statement
     {311, 1}, // 71: declaration_list ->  declaration
     {311, 2}, // 72: declaration_list ->  declaration_list declaration
     {329, 4}, // 73: declaration (';') ->  type_specifier #0003 declarator_list ';'
     {331, 0}, // 74: #0003 ->  <empty>
     {330, 1}, // 75: declarator_list ->  declarator
     {330, 3}, // 76: declarator_list (',') ->  declarator_list ',' declarator
     {332, 1}, // 77: translation_unit_$ ->  translation_unit
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 7} },                       
    { {       300}, { 1} }, // translation_unit   
    { {       301}, { 2} }, // function_definition
    { {       304}, { 3} }, // type_specifier     
    { {       282}, { 4} }, // VOID               
    { {       283}, { 5} }, // INT                
    { {       284}, { 6} }, // FLOAT              
    { {         0}, { 0} },                       
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            7} },                       
    { {       301}, {            7} }, // function_definition
    { {       304}, {            3} }, // type_specifier     
    { {       282}, {            4} }, // VOID               
    { {       283}, {            5} }, // INT                
    { {       284}, {            6} }, // FLOAT              
    { {     _EOF_}, { PARSE_ACCEPT} },                       
    { {         0}, {            0} },                       
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { DEF_RED}, {  2} },         
    { {     302}, {  8} }, // #0001
    { {       0}, { -4} },         
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       305}, {  9} }, // fun_declarator
    { {       277}, { 10} }, // IDENTIFIER    
    { {         0}, {  0} },                  
};

SR__ s_9[] =
{
    { { DEF_RED}, {  2} },         
    { {     303}, { 11} }, // #0002
    { {       0}, { -5} },         
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 12} }, // '('
    { {         0}, {  0} },       
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  3} },                      
    { {       310}, { 13} }, // compound_statement
    { {       123}, { 14} }, // '{'               
    { {         0}, {  0} },                      
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  8} },                         
    { {       306}, { 15} }, // parameter_list       
    { {        41}, { 16} }, // ')'                  
    { {       307}, { 17} }, // parameter_declaration
    { {       304}, { 18} }, // type_specifier       
    { {       282}, {  4} }, // VOID                 
    { {       283}, {  5} }, // INT                  
    { {       284}, {  6} }, // FLOAT                
    { {         0}, {  0} },                         
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, { 21} },                        
    { {       125}, { 19} }, // '}'                 
    { {       312}, { 20} }, // statement_list      
    { {       311}, { 21} }, // declaration_list    
    { {       313}, { 22} }, // statement           
    { {       329}, { 23} }, // declaration         
    { {       123}, { 24} }, // '{'                 
    { {       327}, { 25} }, // selection_statement 
    { {       328}, { 26} }, // iteration_statement 
    { {       314}, { 27} }, // assignment_statement
    { {       296}, { 28} }, // RETURN              
    { {       277}, { 29} }, // IDENTIFIER          
    { {       304}, { 30} }, // type_specifier      
    { {       292}, { 31} }, // IF                  
    { {       294}, { 32} }, // WHILE               
    { {       295}, { 33} }, // FOR                 
    { {        59}, { 34} }, // ';'                 
    { {       324}, { 35} }, // l_expression        
    { {       282}, {  4} }, // VOID                
    { {       283}, {  5} }, // INT                 
    { {       284}, {  6} }, // FLOAT               
    { {         0}, {  0} },                        
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 36} }, // ')'
    { {        44}, { 37} }, // ','
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       308}, { 38} }, // declarator
    { {       277}, { 39} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       125}, { 40} }, // '}'                 
    { {       313}, { 41} }, // statement           
    { {       123}, { 24} }, // '{'                 
    { {       327}, { 25} }, // selection_statement 
    { {       328}, { 26} }, // iteration_statement 
    { {       314}, { 27} }, // assignment_statement
    { {       296}, { 28} }, // RETURN              
    { {       277}, { 29} }, // IDENTIFIER          
    { {       292}, { 31} }, // IF                  
    { {       294}, { 32} }, // WHILE               
    { {       295}, { 33} }, // FOR                 
    { {        59}, { 34} }, // ';'                 
    { {       324}, { 35} }, // l_expression        
    { {         0}, {  0} },                        
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, { 19} },                        
    { {       312}, { 42} }, // statement_list      
    { {       329}, { 43} }, // declaration         
    { {       313}, { 22} }, // statement           
    { {       304}, { 30} }, // type_specifier      
    { {       123}, { 24} }, // '{'                 
    { {       327}, { 25} }, // selection_statement 
    { {       328}, { 26} }, // iteration_statement 
    { {       314}, { 27} }, // assignment_statement
    { {       296}, { 28} }, // RETURN              
    { {       277}, { 29} }, // IDENTIFIER          
    { {       282}, {  4} }, // VOID                
    { {       283}, {  5} }, // INT                 
    { {       284}, {  6} }, // FLOAT               
    { {       292}, { 31} }, // IF                  
    { {       294}, { 32} }, // WHILE               
    { {       295}, { 33} }, // FOR                 
    { {        59}, { 34} }, // ';'                 
    { {       324}, { 35} }, // l_expression        
    { {         0}, {  0} },                        
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       312}, { 44} }, // statement_list      
    { {       313}, { 22} }, // statement           
    { {       123}, { 24} }, // '{'                 
    { {       327}, { 25} }, // selection_statement 
    { {       328}, { 26} }, // iteration_statement 
    { {       314}, { 27} }, // assignment_statement
    { {       296}, { 28} }, // RETURN              
    { {       277}, { 29} }, // IDENTIFIER          
    { {       292}, { 31} }, // IF                  
    { {       294}, { 32} }, // WHILE               
    { {       295}, { 33} }, // FOR                 
    { {        59}, { 34} }, // ';'                 
    { {       324}, { 35} }, // l_expression        
    { {         0}, {  0} },                        
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       315}, { 45} }, // expression               
    { {       316}, { 46} }, // logical_and_expression   
    { {       317}, { 47} }, // equality_expression      
    { {       318}, { 48} }, // relational_expression    
    { {       319}, { 49} }, // additive_expression      
    { {       320}, { 50} }, // multiplicative_expression
    { {       321}, { 51} }, // unary_expression         
    { {       322}, { 52} }, // postfix_expression       
    { {       326}, { 53} }, // unary_operator           
    { {       323}, { 54} }, // primary_expression       
    { {       277}, { 55} }, // IDENTIFIER               
    { {       324}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       278}, { 59} }, // INT_CONSTANT             
    { {       280}, { 60} }, // FLOAT_CONSTANT           
    { {       279}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_29[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  63} }, // '('
    { {       0}, { -62} },       
};

SR__ s_30[] =
{
    { { DEF_RED}, {   2} },         
    { {     331}, {  64} }, // #0003
    { {       0}, { -74} },         
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 65} }, // '('
    { {         0}, {  0} },       
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 66} }, // '('
    { {         0}, {  0} },       
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 67} }, // '('
    { {         0}, {  0} },       
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        61}, { 68} }, // '='
    { {        91}, { 69} }, // '['
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  6} },                         
    { {       307}, { 70} }, // parameter_declaration
    { {       304}, { 18} }, // type_specifier       
    { {       282}, {  4} }, // VOID                 
    { {       283}, {  5} }, // INT                  
    { {       284}, {  6} }, // FLOAT                
    { {         0}, {  0} },                         
};

SR__ s_38[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  71} }, // '['
    { {       0}, { -13} },       
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       125}, { 72} }, // '}'                 
    { {       313}, { 41} }, // statement           
    { {       123}, { 24} }, // '{'                 
    { {       327}, { 25} }, // selection_statement 
    { {       328}, { 26} }, // iteration_statement 
    { {       314}, { 27} }, // assignment_statement
    { {       296}, { 28} }, // RETURN              
    { {       277}, { 29} }, // IDENTIFIER          
    { {       292}, { 31} }, // IF                  
    { {       294}, { 32} }, // WHILE               
    { {       295}, { 33} }, // FOR                 
    { {        59}, { 34} }, // ';'                 
    { {       324}, { 35} }, // l_expression        
    { {         0}, {  0} },                        
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       125}, { 73} }, // '}'                 
    { {       313}, { 41} }, // statement           
    { {       123}, { 24} }, // '{'                 
    { {       327}, { 25} }, // selection_statement 
    { {       328}, { 26} }, // iteration_statement 
    { {       314}, { 27} }, // assignment_statement
    { {       296}, { 28} }, // RETURN              
    { {       277}, { 29} }, // IDENTIFIER          
    { {       292}, { 31} }, // IF                  
    { {       294}, { 32} }, // WHILE               
    { {       295}, { 33} }, // FOR                 
    { {        59}, { 34} }, // ';'                 
    { {       324}, { 35} }, // l_expression        
    { {         0}, {  0} },                        
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {        59}, { 74} }, // ';'  
    { {       287}, { 75} }, // OR_OP
    { {         0}, {  0} },         
};

SR__ s_46[] =
{
    { { REQ_DEF}, {   2} },          
    { {     286}, {  76} }, // AND_OP
    { {       0}, { -32} },          
};

SR__ s_47[] =
{
    { { REQ_DEF}, {   3} },         
    { {     288}, {  77} }, // EQ_OP
    { {     289}, {  78} }, // NE_OP
    { {       0}, { -34} },         
};

SR__ s_48[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  79} }, // '<'  
    { {      62}, {  80} }, // '>'  
    { {     290}, {  81} }, // LE_OP
    { {     291}, {  82} }, // GE_OP
    { {       0}, { -36} },         
};

SR__ s_49[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  83} }, // '+'
    { {      45}, {  84} }, // '-'
    { {       0}, { -39} },       
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  85} }, // '*'
    { {      47}, {  86} }, // '/'
    { {       0}, { -44} },       
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  9} },                      
    { {       322}, { 87} }, // postfix_expression
    { {       323}, { 54} }, // primary_expression
    { {       277}, { 55} }, // IDENTIFIER        
    { {       324}, { 56} }, // l_expression      
    { {       278}, { 59} }, // INT_CONSTANT      
    { {       280}, { 60} }, // FLOAT_CONSTANT    
    { {       279}, { 61} }, // STRING_LITERAL    
    { {        40}, { 62} }, // '('               
    { {         0}, {  0} },                      
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  88} }, // '('
    { {       0}, { -62} },       
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   4} },          
    { {     297}, {  89} }, // INC_OP
    { {      61}, {  90} }, // '='   
    { {      91}, {  69} }, // '['   
    { {       0}, { -56} },          
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       315}, { 91} }, // expression               
    { {       316}, { 46} }, // logical_and_expression   
    { {       317}, { 47} }, // equality_expression      
    { {       318}, { 48} }, // relational_expression    
    { {       319}, { 49} }, // additive_expression      
    { {       320}, { 50} }, // multiplicative_expression
    { {       321}, { 51} }, // unary_expression         
    { {       322}, { 52} }, // postfix_expression       
    { {       326}, { 53} }, // unary_operator           
    { {       323}, { 54} }, // primary_expression       
    { {       277}, { 55} }, // IDENTIFIER               
    { {       324}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       278}, { 59} }, // INT_CONSTANT             
    { {       280}, { 60} }, // FLOAT_CONSTANT           
    { {       279}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 21} },                             
    { {        41}, { 92} }, // ')'                      
    { {       325}, { 93} }, // expression_list          
    { {       315}, { 94} }, // expression               
    { {       316}, { 46} }, // logical_and_expression   
    { {       317}, { 47} }, // equality_expression      
    { {       318}, { 48} }, // relational_expression    
    { {       319}, { 49} }, // additive_expression      
    { {       320}, { 50} }, // multiplicative_expression
    { {       321}, { 51} }, // unary_expression         
    { {       322}, { 52} }, // postfix_expression       
    { {       326}, { 53} }, // unary_operator           
    { {       323}, { 54} }, // primary_expression       
    { {       277}, { 55} }, // IDENTIFIER               
    { {       324}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       278}, { 59} }, // INT_CONSTANT             
    { {       280}, { 60} }, // FLOAT_CONSTANT           
    { {       279}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  4} },                   
    { {       330}, { 95} }, // declarator_list
    { {       308}, { 96} }, // declarator     
    { {       277}, { 39} }, // IDENTIFIER     
    { {         0}, {  0} },                   
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       315}, { 97} }, // expression               
    { {       316}, { 46} }, // logical_and_expression   
    { {       317}, { 47} }, // equality_expression      
    { {       318}, { 48} }, // relational_expression    
    { {       319}, { 49} }, // additive_expression      
    { {       320}, { 50} }, // multiplicative_expression
    { {       321}, { 51} }, // unary_expression         
    { {       322}, { 52} }, // postfix_expression       
    { {       326}, { 53} }, // unary_operator           
    { {       323}, { 54} }, // primary_expression       
    { {       277}, { 55} }, // IDENTIFIER               
    { {       324}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       278}, { 59} }, // INT_CONSTANT             
    { {       280}, { 60} }, // FLOAT_CONSTANT           
    { {       279}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       315}, { 98} }, // expression               
    { {       316}, { 46} }, // logical_and_expression   
    { {       317}, { 47} }, // equality_expression      
    { {       318}, { 48} }, // relational_expression    
    { {       319}, { 49} }, // additive_expression      
    { {       320}, { 50} }, // multiplicative_expression
    { {       321}, { 51} }, // unary_expression         
    { {       322}, { 52} }, // postfix_expression       
    { {       326}, { 53} }, // unary_operator           
    { {       323}, { 54} }, // primary_expression       
    { {       277}, { 55} }, // IDENTIFIER               
    { {       324}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       278}, { 59} }, // INT_CONSTANT             
    { {       280}, { 60} }, // FLOAT_CONSTANT           
    { {       279}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       315}, { 99} }, // expression               
    { {       316}, { 46} }, // logical_and_expression   
    { {       317}, { 47} }, // equality_expression      
    { {       318}, { 48} }, // relational_expression    
    { {       319}, { 49} }, // additive_expression      
    { {       320}, { 50} }, // multiplicative_expression
    { {       321}, { 51} }, // unary_expression         
    { {       322}, { 52} }, // postfix_expression       
    { {       326}, { 53} }, // unary_operator           
    { {       323}, { 54} }, // primary_expression       
    { {       277}, { 55} }, // IDENTIFIER               
    { {       324}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       278}, { 59} }, // INT_CONSTANT             
    { {       280}, { 60} }, // FLOAT_CONSTANT           
    { {       279}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       315}, { 100} }, // expression               
    { {       316}, {  46} }, // logical_and_expression   
    { {       317}, {  47} }, // equality_expression      
    { {       318}, {  48} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       315}, { 101} }, // expression               
    { {       316}, {  46} }, // logical_and_expression   
    { {       317}, {  47} }, // equality_expression      
    { {       318}, {  48} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {   4} },                       
    { {       309}, { 102} }, // constant_expression
    { {       278}, { 103} }, // INT_CONSTANT       
    { {       280}, { 104} }, // FLOAT_CONSTANT     
    { {         0}, {   0} },                       
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  18} },                             
    { {       316}, { 105} }, // logical_and_expression   
    { {       317}, {  47} }, // equality_expression      
    { {       318}, {  48} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  17} },                             
    { {       317}, { 106} }, // equality_expression      
    { {       318}, {  48} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       318}, { 107} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       318}, { 108} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       319}, { 109} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       319}, { 110} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       319}, { 111} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       319}, { 112} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  14} },                             
    { {       320}, { 113} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {  14} },                             
    { {       320}, { 114} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  13} },                      
    { {       321}, { 115} }, // unary_expression  
    { {       322}, {  52} }, // postfix_expression
    { {       326}, {  53} }, // unary_operator    
    { {       323}, {  54} }, // primary_expression
    { {       277}, {  55} }, // IDENTIFIER        
    { {       324}, {  56} }, // l_expression      
    { {        45}, {  57} }, // '-'               
    { {        33}, {  58} }, // '!'               
    { {       278}, {  59} }, // INT_CONSTANT      
    { {       280}, {  60} }, // FLOAT_CONSTANT    
    { {       279}, {  61} }, // STRING_LITERAL    
    { {        40}, {  62} }, // '('               
    { {         0}, {   0} },                      
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  13} },                      
    { {       321}, { 116} }, // unary_expression  
    { {       322}, {  52} }, // postfix_expression
    { {       326}, {  53} }, // unary_operator    
    { {       323}, {  54} }, // primary_expression
    { {       277}, {  55} }, // IDENTIFIER        
    { {       324}, {  56} }, // l_expression      
    { {        45}, {  57} }, // '-'               
    { {        33}, {  58} }, // '!'               
    { {       278}, {  59} }, // INT_CONSTANT      
    { {       280}, {  60} }, // FLOAT_CONSTANT    
    { {       279}, {  61} }, // STRING_LITERAL    
    { {        40}, {  62} }, // '('               
    { {         0}, {   0} },                      
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {        41}, { 117} }, // ')'                      
    { {       325}, { 118} }, // expression_list          
    { {       315}, {  94} }, // expression               
    { {       316}, {  46} }, // logical_and_expression   
    { {       317}, {  47} }, // equality_expression      
    { {       318}, {  48} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       315}, { 119} }, // expression               
    { {       316}, {  46} }, // logical_and_expression   
    { {       317}, {  47} }, // equality_expression      
    { {       318}, {  48} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 120} }, // ')'  
    { {       287}, {  75} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 121} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 122} }, // ')'
    { {        44}, { 123} }, // ','
    { {         0}, {   0} },       
};

SR__ s_94[] =
{
    { { REQ_DEF}, {   2} },         
    { {     287}, {  75} }, // OR_OP
    { {       0}, { -64} },         
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        59}, { 124} }, // ';'
    { {        44}, { 125} }, // ','
    { {         0}, {   0} },       
};

SR__ s_96[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  71} }, // '['
    { {       0}, { -75} },       
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 126} }, // ')'  
    { {       287}, {  75} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 127} }, // ')'  
    { {       287}, {  75} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        59}, { 128} }, // ';'  
    { {       287}, {  75} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        59}, { 129} }, // ';'  
    { {       287}, {  75} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        93}, { 130} }, // ']'  
    { {       287}, {  75} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        93}, { 131} }, // ']'
    { {         0}, {   0} },       
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_104[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_105[] =
{
    { { REQ_DEF}, {   2} },          
    { {     286}, {  76} }, // AND_OP
    { {       0}, { -33} },          
};

SR__ s_106[] =
{
    { { REQ_DEF}, {   3} },         
    { {     288}, {  77} }, // EQ_OP
    { {     289}, {  78} }, // NE_OP
    { {       0}, { -35} },         
};

SR__ s_107[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  79} }, // '<'  
    { {      62}, {  80} }, // '>'  
    { {     290}, {  81} }, // LE_OP
    { {     291}, {  82} }, // GE_OP
    { {       0}, { -37} },         
};

SR__ s_108[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  79} }, // '<'  
    { {      62}, {  80} }, // '>'  
    { {     290}, {  81} }, // LE_OP
    { {     291}, {  82} }, // GE_OP
    { {       0}, { -38} },         
};

SR__ s_109[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  83} }, // '+'
    { {      45}, {  84} }, // '-'
    { {       0}, { -40} },       
};

SR__ s_110[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  83} }, // '+'
    { {      45}, {  84} }, // '-'
    { {       0}, { -41} },       
};

SR__ s_111[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  83} }, // '+'
    { {      45}, {  84} }, // '-'
    { {       0}, { -42} },       
};

SR__ s_112[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  83} }, // '+'
    { {      45}, {  84} }, // '-'
    { {       0}, { -43} },       
};

SR__ s_113[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  85} }, // '*'
    { {      47}, {  86} }, // '/'
    { {       0}, { -45} },       
};

SR__ s_114[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  85} }, // '*'
    { {      47}, {  86} }, // '/'
    { {       0}, { -46} },       
};

SR__ s_115[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_118[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 132} }, // ')'
    { {        44}, { 123} }, // ','
    { {         0}, {   0} },       
};

SR__ s_119[] =
{
    { { REQ_DEF}, {   2} },         
    { {     287}, {  75} }, // OR_OP
    { {       0}, { -57} },         
};

SR__ s_120[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_122[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 133} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_123[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       315}, { 134} }, // expression               
    { {       316}, {  46} }, // logical_and_expression   
    { {       317}, {  47} }, // equality_expression      
    { {       318}, {  48} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_124[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_125[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       308}, { 135} }, // declarator
    { {       277}, {  39} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_126[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       313}, { 136} }, // statement           
    { {       123}, {  24} }, // '{'                 
    { {       327}, {  25} }, // selection_statement 
    { {       328}, {  26} }, // iteration_statement 
    { {       314}, {  27} }, // assignment_statement
    { {       296}, {  28} }, // RETURN              
    { {       277}, {  29} }, // IDENTIFIER          
    { {       292}, {  31} }, // IF                  
    { {       294}, {  32} }, // WHILE               
    { {       295}, {  33} }, // FOR                 
    { {        59}, {  34} }, // ';'                 
    { {       324}, {  35} }, // l_expression        
    { {         0}, {   0} },                        
};

SR__ s_127[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       313}, { 137} }, // statement           
    { {       123}, {  24} }, // '{'                 
    { {       327}, {  25} }, // selection_statement 
    { {       328}, {  26} }, // iteration_statement 
    { {       314}, {  27} }, // assignment_statement
    { {       296}, {  28} }, // RETURN              
    { {       277}, {  29} }, // IDENTIFIER          
    { {       292}, {  31} }, // IF                  
    { {       294}, {  32} }, // WHILE               
    { {       295}, {  33} }, // FOR                 
    { {        59}, {  34} }, // ';'                 
    { {       324}, {  35} }, // l_expression        
    { {         0}, {   0} },                        
};

SR__ s_128[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       315}, { 138} }, // expression               
    { {       316}, {  46} }, // logical_and_expression   
    { {       317}, {  47} }, // equality_expression      
    { {       318}, {  48} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_129[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_130[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_131[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_132[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_133[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_134[] =
{
    { { REQ_DEF}, {   2} },         
    { {     287}, {  75} }, // OR_OP
    { {       0}, { -65} },         
};

SR__ s_135[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  71} }, // '['
    { {       0}, { -76} },       
};

SR__ s_136[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       293}, { 139} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_137[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_138[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        59}, { 140} }, // ';'  
    { {       287}, {  75} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_139[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       313}, { 141} }, // statement           
    { {       123}, {  24} }, // '{'                 
    { {       327}, {  25} }, // selection_statement 
    { {       328}, {  26} }, // iteration_statement 
    { {       314}, {  27} }, // assignment_statement
    { {       296}, {  28} }, // RETURN              
    { {       277}, {  29} }, // IDENTIFIER          
    { {       292}, {  31} }, // IF                  
    { {       294}, {  32} }, // WHILE               
    { {       295}, {  33} }, // FOR                 
    { {        59}, {  34} }, // ';'                 
    { {       324}, {  35} }, // l_expression        
    { {         0}, {   0} },                        
};

SR__ s_140[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       315}, { 142} }, // expression               
    { {       316}, {  46} }, // logical_and_expression   
    { {       317}, {  47} }, // equality_expression      
    { {       318}, {  48} }, // relational_expression    
    { {       319}, {  49} }, // additive_expression      
    { {       320}, {  50} }, // multiplicative_expression
    { {       321}, {  51} }, // unary_expression         
    { {       322}, {  52} }, // postfix_expression       
    { {       326}, {  53} }, // unary_operator           
    { {       323}, {  54} }, // primary_expression       
    { {       277}, {  55} }, // IDENTIFIER               
    { {       324}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       278}, {  59} }, // INT_CONSTANT             
    { {       280}, {  60} }, // FLOAT_CONSTANT           
    { {       279}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_141[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_142[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 143} }, // ')'  
    { {       287}, {  75} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_143[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       313}, { 144} }, // statement           
    { {       123}, {  24} }, // '{'                 
    { {       327}, {  25} }, // selection_statement 
    { {       328}, {  26} }, // iteration_statement 
    { {       314}, {  27} }, // assignment_statement
    { {       296}, {  28} }, // RETURN              
    { {       277}, {  29} }, // IDENTIFIER          
    { {       292}, {  31} }, // IF                  
    { {       294}, {  32} }, // WHILE               
    { {       295}, {  33} }, // FOR                 
    { {        59}, {  34} }, // ';'                 
    { {       324}, {  35} }, // l_expression        
    { {         0}, {   0} },                        
};

SR__ s_144[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


Meta__::SType ParserBase::d_val__;
void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 35 "parse.y"
        {
         
         gencode(d_vsp__[0].data<Tag__::STMT>(), current_func_name);
         if(printables.find(current_func_name)!=printables.end()){
         d_vsp__[0].data<Tag__::STMT>()->print();
         }
         }
        break;

        case 2:
#line 43 "parse.y"
        {
         d_val__.get<Tag__::STMT>() = d_vsp__[-1].data<Tag__::STMT>();
         
         gencode(d_vsp__[0].data<Tag__::STMT>(), current_func_name);
         if(printables.find(current_func_name)!=printables.end()){
         d_vsp__[0].data<Tag__::STMT>()->print();
         }
         }
        break;

        case 3:
#line 75 "parse.y"
        {
         if(!does_return && d_vsp__[-4].data<Tag__::TYPE_STRING>()!="void"){
         add_error(Scanner::line_num, "function must return "+current_func_type);
         }
         d_val__.get<Tag__::STMT>() = d_vsp__[0].data<Tag__::STMT>();
         }
        break;

        case 4:
#line 56 "parse.y"
        d_val__ = d_vsp__[0];
        {
         current_scope = new symbol_table;
         current_scope->offset = 4; 
         does_return=false;
         current_func_type=d_vsp__[0].data<Tag__::TYPE_STRING>();
         }
        break;

        case 5:
#line 63 "parse.y"
        d_val__ = d_vsp__[-2];
        {
         current_scope->offset=0;
         if(check_declaration_function(d_vsp__[0].data<Tag__::TYPE_STRING>()))
         {
         symbol_table_node* stn = new symbol_table_node(d_vsp__[0].data<Tag__::TYPE_STRING>(), "function", current_scope);
         decl_struct *temp = new decl_struct(d_vsp__[0].data<Tag__::TYPE_STRING>());
         temp->type = d_vsp__[-2].data<Tag__::TYPE_STRING>();
         stn->decl_type = temp;
         gst->insert_entry(d_vsp__[0].data<Tag__::TYPE_STRING>(), stn);
         current_func_name=d_vsp__[0].data<Tag__::TYPE_STRING>();
         }
         }
        break;

        case 6:
#line 86 "parse.y"
        {
         d_val__.get<Tag__::TYPE_STRING>()=d_vsp__[0].data<Tag__::TYPE_STRING>();
         }
        break;

        case 7:
#line 90 "parse.y"
        {
         d_val__.get<Tag__::TYPE_STRING>()=d_vsp__[0].data<Tag__::TYPE_STRING>();
         }
        break;

        case 8:
#line 94 "parse.y"
        {
         d_val__.get<Tag__::TYPE_STRING>()=d_vsp__[0].data<Tag__::TYPE_STRING>();
         }
        break;

        case 9:
#line 102 "parse.y"
        {
         d_val__.get<Tag__::TYPE_STRING>() = d_vsp__[-3].data<Tag__::TYPE_STRING>();
         }
        break;

        case 10:
#line 106 "parse.y"
        {
         d_val__.get<Tag__::TYPE_STRING>() = d_vsp__[-2].data<Tag__::TYPE_STRING>();
         }
        break;

        case 13:
#line 119 "parse.y"
        {
         
         
         if(check_declaration((d_vsp__[0].data<Tag__::DEC_STR>())->name,d_vsp__[-1].data<Tag__::TYPE_STRING>()))
         {
         
         
         (d_vsp__[0].data<Tag__::DEC_STR>())->type = d_vsp__[-1].data<Tag__::TYPE_STRING>();
         
         symbol_table_node* temp = new symbol_table_node((d_vsp__[0].data<Tag__::DEC_STR>())->name,d_vsp__[-1].data<Tag__::TYPE_STRING>(),current_scope->offset);
         temp->type = "param";
         temp->decl_type = d_vsp__[0].data<Tag__::DEC_STR>();
         temp->size = (d_vsp__[0].data<Tag__::DEC_STR>())->calculate_size();
         current_scope->insert_entry(temp->name,temp);
         current_scope->offset = current_scope->offset + temp->size;
         
         
         
         current_scope->parameters.push_back(d_vsp__[0].data<Tag__::DEC_STR>());
         }
         }
        break;

        case 14:
#line 145 "parse.y"
        {
         d_val__.get<Tag__::DEC_STR>() = new decl_struct(d_vsp__[0].data<Tag__::TYPE_STRING>());
         }
        break;

        case 15:
#line 149 "parse.y"
        {
         
         if(check_int((d_vsp__[-1].data<Tag__::DEC_STR>())->type)){
         ((d_vsp__[-3].data<Tag__::DEC_STR>())->indices).push_back(stoi((d_vsp__[-1].data<Tag__::DEC_STR>())->name));
         d_val__.get<Tag__::DEC_STR>() = d_vsp__[-3].data<Tag__::DEC_STR>();
         }
         }
        break;

        case 16:
#line 161 "parse.y"
        {
         d_val__.get<Tag__::DEC_STR>() = new decl_struct(d_vsp__[0].data<Tag__::TYPE_STRING>());
         (d_val__.get<Tag__::DEC_STR>())->type="int";
         }
        break;

        case 17:
#line 166 "parse.y"
        {
         d_val__.get<Tag__::DEC_STR>() = new decl_struct(d_vsp__[0].data<Tag__::TYPE_STRING>());
         (d_val__.get<Tag__::DEC_STR>())->type="float";
         }
        break;

        case 19:
#line 176 "parse.y"
        { 
         d_val__.get<Tag__::STMT>() = new block_node(d_vsp__[-1].data<Tag__::STMT_LIST>());
         }
        break;

        case 20:
#line 180 "parse.y"
        {
         d_val__.get<Tag__::STMT>() = new block_node(d_vsp__[-1].data<Tag__::STMT_LIST>());
         }
        break;

        case 21:
#line 187 "parse.y"
        {
         d_val__.get<Tag__::STMT_LIST>() = new stmt_node_list();
         (d_val__.get<Tag__::STMT_LIST>())->add_stmt(d_vsp__[0].data<Tag__::STMT>());
         }
        break;

        case 22:
#line 192 "parse.y"
        {
         (d_vsp__[-1].data<Tag__::STMT_LIST>())->add_stmt(d_vsp__[0].data<Tag__::STMT>());
         d_val__.get<Tag__::STMT_LIST>() = d_vsp__[-1].data<Tag__::STMT_LIST>();
         }
        break;

        case 23:
#line 200 "parse.y"
        {
         d_val__.get<Tag__::STMT>() = new block_node(d_vsp__[-1].data<Tag__::STMT_LIST>());
         }
        break;

        case 24:
#line 204 "parse.y"
        {
         d_val__.get<Tag__::STMT>() = d_vsp__[0].data<Tag__::STMT>(); 
         }
        break;

        case 25:
#line 208 "parse.y"
        {
         d_val__.get<Tag__::STMT>() = d_vsp__[0].data<Tag__::STMT>();
         }
        break;

        case 26:
#line 212 "parse.y"
        {
         d_val__.get<Tag__::STMT>() = d_vsp__[0].data<Tag__::STMT>();
         }
        break;

        case 27:
#line 216 "parse.y"
        {
         
         if(check_return_expression(d_vsp__[-1].data<Tag__::EXP>())){
         does_return = true;
         d_val__.get<Tag__::STMT>() = new return_node(d_vsp__[-1].data<Tag__::EXP>());
         }
         }
        break;

        case 28:
#line 224 "parse.y"
        {
         
         exp_node_list* temp_list = new exp_node_list();
         if(valid_funcall(d_vsp__[-3].data<Tag__::TYPE_STRING>(), temp_list)){
         d_val__.get<Tag__::STMT>() = new funcall_stmt_node(d_vsp__[-3].data<Tag__::TYPE_STRING>(), temp_list);
         }
         }
        break;

        case 29:
#line 232 "parse.y"
        {
         
         if(valid_funcall(d_vsp__[-4].data<Tag__::TYPE_STRING>(), d_vsp__[-2].data<Tag__::EXP_LIST>())){
         d_val__.get<Tag__::STMT>() = new funcall_stmt_node(d_vsp__[-4].data<Tag__::TYPE_STRING>(), d_vsp__[-2].data<Tag__::EXP_LIST>());
         }
         }
        break;

        case 30:
#line 242 "parse.y"
        {
         d_val__.get<Tag__::STMT>() = new stmt_node();
         }
        break;

        case 31:
#line 246 "parse.y"
        {
         if(check_int_float(d_vsp__[-1].data<Tag__::EXP>()->type->type)&&check_type(d_vsp__[-3].data<Tag__::EXP>(), d_vsp__[-1].data<Tag__::EXP>())){
         (d_vsp__[-3].data<Tag__::EXP>())->retOff=1;
         d_val__.get<Tag__::STMT>() = new ass_node(d_vsp__[-3].data<Tag__::EXP>(),d_vsp__[-1].data<Tag__::EXP>());
         }
         }
        break;

        case 32:
#line 256 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[0].data<Tag__::EXP>();
         }
        break;

        case 33:
#line 260 "parse.y"
        {
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "OR";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         }
         }
        break;

        case 34:
#line 273 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[0].data<Tag__::EXP>();
         }
        break;

        case 35:
#line 277 "parse.y"
        { 
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "AND";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>()); 
         }
         }
        break;

        case 36:
#line 290 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[0].data<Tag__::EXP>();
         }
        break;

        case 37:
#line 294 "parse.y"
        { 
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "EQ";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         }
         }
        break;

        case 38:
#line 304 "parse.y"
        {
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "NE";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         }
         }
        break;

        case 39:
#line 317 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[0].data<Tag__::EXP>();
         }
        break;

        case 40:
#line 321 "parse.y"
        {
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "LT";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         }
         }
        break;

        case 41:
#line 331 "parse.y"
        { 
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "GT";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         }
         }
        break;

        case 42:
#line 341 "parse.y"
        {
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "LE";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>()); 
         }
         }
        break;

        case 43:
#line 351 "parse.y"
        { 
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "GE";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>()); 
         }
         }
        break;

        case 44:
#line 364 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[0].data<Tag__::EXP>(); 
         }
        break;

        case 45:
#line 368 "parse.y"
        {
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "PLUS";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         
         }
         }
        break;

        case 46:
#line 379 "parse.y"
        {
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "MINUS";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         
         }
         }
        break;

        case 47:
#line 393 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[0].data<Tag__::EXP>();
         }
        break;

        case 48:
#line 397 "parse.y"
        {
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "MULTIPLY";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         
         
         }
         }
        break;

        case 49:
#line 409 "parse.y"
        {
         
         
         if(check_int_float((d_vsp__[-2].data<Tag__::EXP>())->type->type)&&check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)&&check_arith_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>())){
         string k;
         k = "DIVIDE";
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         
         }
         }
        break;

        case 50:
#line 423 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[0].data<Tag__::EXP>();
         }
        break;

        case 51:
#line 427 "parse.y"
        {
         if(check_int_float((d_vsp__[0].data<Tag__::EXP>())->type->type)){
         d_val__.get<Tag__::EXP>() = new unary_op_node(d_vsp__[-1].data<Tag__::TYPE_STRING>() , d_vsp__[0].data<Tag__::EXP>());
         }
         }
        break;

        case 52:
#line 436 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[0].data<Tag__::EXP>();
         }
        break;

        case 53:
#line 440 "parse.y"
        { 
         exp_node_list* temp_list = new exp_node_list();
         if(valid_funcall(d_vsp__[-2].data<Tag__::TYPE_STRING>(), temp_list)&&check_printf((d_vsp__[-2].data<Tag__::TYPE_STRING>()))){
         d_val__.get<Tag__::EXP>() = new funcall_node(d_vsp__[-2].data<Tag__::TYPE_STRING>(), temp_list);
         }
         }
        break;

        case 54:
#line 447 "parse.y"
        {
         
         if(valid_funcall(d_vsp__[-3].data<Tag__::TYPE_STRING>(), d_vsp__[-1].data<Tag__::EXP_LIST>())&&check_printf((d_vsp__[-3].data<Tag__::TYPE_STRING>()))){
         d_val__.get<Tag__::EXP>() = new funcall_node(d_vsp__[-3].data<Tag__::TYPE_STRING>(), d_vsp__[-1].data<Tag__::EXP_LIST>());
         }
         }
        break;

        case 55:
#line 454 "parse.y"
        {
         
         if(check_int_float(d_vsp__[-1].data<Tag__::EXP>()->type->type)){
         string k = "PP";
         (d_vsp__[-1].data<Tag__::EXP>())->retOff=1;
         d_val__.get<Tag__::EXP>() = new unary_op_node(k,d_vsp__[-1].data<Tag__::EXP>());
         }
         }
        break;

        case 56:
#line 466 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[0].data<Tag__::EXP>();
         }
        break;

        case 57:
#line 470 "parse.y"
        {
         
         
         
         if(check_int_float(d_vsp__[0].data<Tag__::EXP>()->type->type)&&check_type(d_vsp__[-2].data<Tag__::EXP>(), d_vsp__[0].data<Tag__::EXP>()))
         {
         string k ="ASSIGN";
         (d_vsp__[-2].data<Tag__::EXP>())->retOff=1;
         d_val__.get<Tag__::EXP>() = new op_node(k,d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::EXP>());
         }
         }
        break;

        case 58:
#line 482 "parse.y"
        {
         
         d_val__.get<Tag__::EXP>() = new intconst_node(d_vsp__[0].data<Tag__::TYPE_STRING>());
         }
        break;

        case 59:
#line 487 "parse.y"
        {
         
         d_val__.get<Tag__::EXP>() = new floatconst_node(d_vsp__[0].data<Tag__::TYPE_STRING>()); 
         }
        break;

        case 60:
#line 492 "parse.y"
        {
         
         d_val__.get<Tag__::EXP>() = new stringconst_node(d_vsp__[0].data<Tag__::TYPE_STRING>());
         }
        break;

        case 61:
#line 497 "parse.y"
        {
         d_val__.get<Tag__::EXP>() = d_vsp__[-1].data<Tag__::EXP>();
         }
        break;

        case 62:
#line 504 "parse.y"
        {
         
         if(check_declared(d_vsp__[0].data<Tag__::TYPE_STRING>())){
         d_val__.get<Tag__::EXP>() = new array_ref_node(d_vsp__[0].data<Tag__::TYPE_STRING>()); 
         }
         }
        break;

        case 63:
#line 512 "parse.y"
        {
         if(check_inbound(d_vsp__[-3].data<Tag__::EXP>())&&check_int((d_vsp__[-1].data<Tag__::EXP>())->type->type)){
         (d_vsp__[-3].data<Tag__::EXP>())->isIndex=0;
         (d_vsp__[-3].data<Tag__::EXP>())->exp->push_back(d_vsp__[-1].data<Tag__::EXP>()); 
         (d_vsp__[-3].data<Tag__::EXP>())->type->indices.erase((d_vsp__[-3].data<Tag__::EXP>())->type->indices.begin()); 
         d_val__.get<Tag__::EXP>()=d_vsp__[-3].data<Tag__::EXP>();
         }
         }
        break;

        case 64:
#line 524 "parse.y"
        {
         d_val__.get<Tag__::EXP_LIST>() = new exp_node_list();
         (d_val__.get<Tag__::EXP_LIST>())->add_exp(d_vsp__[0].data<Tag__::EXP>());
         }
        break;

        case 65:
#line 529 "parse.y"
        {
         (d_vsp__[-2].data<Tag__::EXP_LIST>())->add_exp(d_vsp__[0].data<Tag__::EXP>());
         d_val__.get<Tag__::EXP_LIST>() = d_vsp__[-2].data<Tag__::EXP_LIST>();
         }
        break;

        case 66:
#line 537 "parse.y"
        {
         d_val__.get<Tag__::TYPE_STRING>() = "-";
         }
        break;

        case 67:
#line 541 "parse.y"
        {
         d_val__.get<Tag__::TYPE_STRING>() = "!";
         }
        break;

        case 68:
#line 548 "parse.y"
        {
         
         if(check_logical_type(d_vsp__[-4].data<Tag__::EXP>())){
         d_val__.get<Tag__::STMT>() = new if_node(d_vsp__[-4].data<Tag__::EXP>(),d_vsp__[-2].data<Tag__::STMT>(),d_vsp__[0].data<Tag__::STMT>());
         }
         }
        break;

        case 69:
#line 558 "parse.y"
        {
         
         if(check_logical_type(d_vsp__[-2].data<Tag__::EXP>())){
         d_val__.get<Tag__::STMT>() = new while_node(d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::STMT>());
         }
         }
        break;

        case 70:
#line 565 "parse.y"
        {
         
         if(check_logical_type(d_vsp__[-4].data<Tag__::EXP>())){
         d_val__.get<Tag__::STMT>() = new for_node(d_vsp__[-6].data<Tag__::EXP>(),d_vsp__[-4].data<Tag__::EXP>(),d_vsp__[-2].data<Tag__::EXP>(),d_vsp__[0].data<Tag__::STMT>());
         }
         }
        break;

        case 74:
#line 579 "parse.y"
        d_val__ = d_vsp__[0];
        {temp_type = d_vsp__[0].data<Tag__::TYPE_STRING>();}
        break;

        case 75:
#line 584 "parse.y"
        {
         (d_vsp__[0].data<Tag__::DEC_STR>())->type = temp_type;
         
         if(check_declaration((d_vsp__[0].data<Tag__::DEC_STR>())->name,temp_type)){
         symbol_table_node* temp = new symbol_table_node((d_vsp__[0].data<Tag__::DEC_STR>())->name,temp_type,current_scope->offset);
         temp->type = "local";
         temp->decl_type = d_vsp__[0].data<Tag__::DEC_STR>();
         temp->size = (d_vsp__[0].data<Tag__::DEC_STR>())->calculate_size();
         current_scope->offset = current_scope->offset - temp->size;
         temp->offset = current_scope->offset;
         current_scope->insert_entry(temp->name,temp);
         
         
         }
         }
        break;

        case 76:
#line 600 "parse.y"
        {
         (d_vsp__[0].data<Tag__::DEC_STR>())->type = temp_type;
         
         if(check_declaration((d_vsp__[0].data<Tag__::DEC_STR>())->name,temp_type)){
         symbol_table_node* temp = new symbol_table_node((d_vsp__[0].data<Tag__::DEC_STR>())->name,temp_type,current_scope->offset);
         temp->type = "local";
         temp->decl_type = d_vsp__[0].data<Tag__::DEC_STR>();
         temp->size = (d_vsp__[0].data<Tag__::DEC_STR>())->calculate_size();
         current_scope->offset = current_scope->offset - temp->size;
         temp->offset = current_scope->offset;
         current_scope->insert_entry(temp->name,temp);
         
         
         }
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

// $insert polymorphicImpl
namespace Meta__
{
   Base::~Base()
   {}
}




